Created At: 2026-07-03T01:20:16Z
Completed At: 2026-07-03T01:20:17Z
File Path: `file:///d:/Github/eworker/banner_tc_039d4f46-f335-42f5-bf3c-55e209fe36e0_step10.py`
Total Lines: 2
Total Bytes: 2072
Showing lines 1 to 2
The following code has been modified to include a line number before every line, in the format: <line_number>: <original_line>. Please note that any changes targeting the original code should remove the line number, colon, and leading space.
1: "import os\nimport sys\nfrom PIL import Image, ImageDraw, ImageFont\n\n# Add directory of screenshot_donate.py to path\nsys.path.append(r\"d:\\Github\\eworker\")\n\nfrom screenshot_donate import preprocess_thai_text\n\ndef create_ad_banner_new(width):\n    \"\"\"สร้างแถบโฆษณาสวยๆ ขนาดเท่ากับความกว้างของภาพ (รองรับ Emoji สี)\"\"\"\n    scale = max(0.85, min(width / 900.0, 2.5))\n    banner_h = int(120 * scale)\n    \n    # สร้างแถบ gradient สีน้ำเงิน ดูมืออาชีพน่าไว้วางใจ (น้ำเงินเข้ม -> น้ำเงินสว่าง)\n    grad = Image.new('RGBA', (2, 1))\n    grad.putpixel((0, 0), (10, 46, 92, 255))   # Dark Blue\n    grad.putpixel((1, 0), (21, 95, 160, 255))  # Professional lighter Blue\n    \n    try:\n        resample_filter = Image.Resampling.BILINEAR\n    except AttributeError:\n        resample_filter = Image.BILINEAR\n    banner = grad.resize((width, banner_h), resample_filter)\n    draw = ImageDraw.Draw(banner)\n    \n    # เส้นคั่น/เส้นปะสีขาวและกรรไกรด้านขวา\n    # เราจะวาดเส้นรอยปะสีขาวที่ด้านล่างของแบนเนอร์\n    accent_h = max(2, int(3 * scale))\n    # แต่ผู้ใช้ขอกรอบล่างเป็นรอยปะขาว\n    dash_w = int(10 * scale)\n    dash_g = int(6 * scale)\n    line_y = banner_h - int(6 * scale)\n    line_thickness = max(1, int(2 * scale))\n    \n    # เว้นที่ทางขวาสำหรับกรรไกรตัด\n    scissors_width = int(50 * scale)\n    end_x = width - scissors_width\n    \n    # วาดเส้นปะขาว\n    for x in range(0, end_x, dash_w + dash_g):\n        draw.line([(x, line_y), (min(x + dash_w, end_x), line_y)], fill=(255, 255, 255, 220),
2: <truncated 8141 bytes>
The above content shows the entire, complete file contents of the requested file.
