Created At: 2026-07-03T01:20:43Z
Completed At: 2026-07-03T01:20:43Z
File Path: `file:///d:/Github/eworker/banner_tc_0bea6a47-896d-49e1-a5ff-dd34ea443860_step10.py`
Total Lines: 2
Total Bytes: 2072
Showing lines 1 to 2
The following code has been modified to include a line number before every line, in the format: <line_number>: <original_line>. Please note that any changes targeting the original code should remove the line number, colon, and leading space.
1: "def create_ad_banner(width):\n    \"\"\"สร้างแถบโฆษณาสวยๆ ขนาดเท่ากับความกว้างของภาพ (รองรับ Emoji สี)\"\"\"\n    scale = max(0.85, min(width / 900.0, 2.5))\n    banner_h = int(95 * scale)\n    \n    # สร้างแถบ gradient สีเหลือง (เหลืองเข้ม -> เหลืองอ่อน)\n    banner = Image.new('RGBA', (width, banner_h), (253, 224, 71, 255))\n    draw = ImageDraw.Draw(banner)\n    \n    # วาด gradient background (จาก Yellow-300: 253, 224, 71 ถึง Yellow-500: 234, 179, 8)\n    for x in range(width):\n        ratio = x / width\n        r = int(253 - ratio * 19)\n        g = int(224 - ratio * 45)\n        b = int(71 - ratio * 63)\n        draw.line([(x, 0), (x, banner_h)], fill=(r, g, b, 255))\n    \n    # เส้นคั่นสีส้ม/น้ำตาลทองด้านล่าง\n    accent_h = max(2, int(3 * scale))\n    draw.rectangle([0, banner_h - accent_h, width - 1, banner_h - 1], fill=(180, 83, 9, 255))\n    \n    # โหลดฟอนต์: emoji, ข้อความหลัก, ข้อความรอง\n    emoji_size = int(26 * scale)\n    text_size = int(22 * scale)\n    sub_size = int(15 * scale)\n    \n    font_emoji = None\n    for fp in [\"C:/Windows/Fonts/seguiemj.ttf\"]:\n        if os.path.exists(fp):\n            font_emoji = ImageFont.truetype(fp, emoji_size)\n            break\n    \n    font_main = None\n    for fp in [\"C:/Windows/Fonts/tahomabd.ttf\", \"C:/Windows/Fonts/arialbd.ttf\", \"C:/Windows/Fonts/tahoma.ttf\", \"C:/Windows/Fonts/arial.ttf\"]:\n        if os.path.exists(fp):\n            font_main = ImageFont.truetype(fp, text_size)\n            break\n    if not font_main:\n        font_main = ImageFont.load_default()\n        \n    font_sub = None\n    for fp in [\"C:/Windows/Fonts/tahoma.ttf\", \"C:/Windows/Fonts/arial.ttf\"]:\n        if os.path.exists(fp):\n            font_sub =
2: <truncated 5790 bytes>
The above content shows the entire, complete file contents of the requested file.
